---
title: "Lab4_R4L"
author: "R4L"
date: "2/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
babies <- read_csv("https://raw.githubusercontent.com/ervance1/Sp2018-Data-Science-repo/master/babies2a.dat")
babies <- rename(babies, bwtoz = `bwt/oz`)
```

```{r}
babies <- babies %>%
  mutate(mrace2 = ifelse(mrace <= 5, 1, mrace))
```

```{r}
babies <- babies %>%
  mutate(mrace2 = ifelse(mrace <= 5, 1, mrace))

ggplot(data=babies, aes(x= med, fill=as.factor(mrace))) +
  geom_bar(position = "dodge")+
  scale_fill_discrete(name = "Women's Race",
                      labels = c('White', 'Black', 'Asian', 'Mix', 'Unknown'))+
  xlab('Mothers Education')
  babies <-na.omit(babies)

```

```{r}
ggplot(data=babies)+
  geom_bar(mapping = aes(x=bwtoz, fill = as.factor(smoke)), position = "dodge")+
  ggtitle('How smoking can affect babies body weight')+
  scale_fill_discrete(name = 'Does Mother Smoke',
                       labels = c('Yes', 'No'))
```

```{r}
babies<-na.omit(babies)
ggplot(data = babies, aes(x = as.factor(parity), fill =as.factor(inc)))+
  geom_bar(position = 'dodge')+
  scale_fill_discrete(name = 'Income',
                      labels = c('Under $2500', '$2500-$4999', '$5000-$9999', '$10000-$19999', '$20000-$29999', '$30000-$49999', '$50000-$74999', '$75000-$99999', '$100000-$149999', '$150000+'))+
  xlab('Number of Previous Pregnancies')
 
cor(babies$parity, babies$inc)



```
```{r}
ggplot(data=babies, aes(x=bwtoz, y=gestation))+
  geom_point()
```

###Baiyu's part: 
```{r} 
require(ggplot2) 
library(dplyr) 
 
babies <-na.omit(babies) 
 
babies <- babies %>% 
  mutate(med2 = ifelse(med==7 , 6, med)) 
 
ggplot(data = babies)+ 
  geom_jitter(mapping = aes(x=med2, y=mage, color=as.factor(med2)))+ 
  facet_wrap(~smoke,labeller=labeller(smoke = c('0' = 'Never Smoke', '1' = 'Smoke Now')))+ 
   scale_color_discrete(name = 'Mothers education',                                     labels = c('0 = less than 8th grade', '1 = 8th to 12th grade. did not graduate high school', '2 = high school graduate, no other schooling', '3 = high school graduate + trade school', '4 = high school graduate + some college', '5 = college graduate', '6 = trade school but unclear if graduated from high school'))+ 
  scale_x_continuous(breaks=c(0,1,2,3,4,5,6),labels = c('0','1','2','3','4','5','6'))+ 
  theme_grey()+ 
  xlab("Mothers Education")+ 
  ylab("Mothers Age")+ 
  ggtitle("Educated Level Between Smoker and Non-smoker") 
``` 
